#!/bin/bash
alias dotfiles="subl -n ~/.dotfiles"
alias dotfiles-remove='~/.dotfiles/setup/remove.sh'
alias dotfiles-install='~/.dotfiles/setup/install.sh'
alias shellconfig='subl ~/.usershell;'
alias zshconfig='subl ~/.zshrc; subl ~/.zprofile; subl subl ~/.zlogin; subl ~/.zlogout'
alias preztoconfig='subl ~/.zpreztorc; subl ~/.zshenv; subl ~/.zprofile; subl ~/.zshrc; subl ~/.zshenv; subl ~/.zlogin; subl ~/.zlogout'
alias bashconfig='subl ~/.bash_profile; subl ~/.bashrc'
alias gitconfig='subl ~/.gitconfig; subl ~/.gitignore_global'
alias slt='subl'
alias c='clear'
alias wget='wget -c' # Resume wget by default
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localip='ipconfig getifaddr en0;ipconfig getifaddr en1;'
alias ls='ls -G'
alias ll='ls -lh'
alias l.='ls -d -G .*'
alias npml='npm list -g --depth=0'
alias brewl='brew leaves'
alias showHidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideHidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias afk="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
alias lock="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias sleeping="pmset sleepnow"
alias hideDesktop='defaults write com.apple.finder CreateDesktop -bool false; killall Finder;'
alias showDesktop='defaults write com.apple.finder CreateDesktop -bool true; killall Finder;'
alias gitjk="history 10 | tail -r | gitjk_cmd"
alias net='sudo lsof -i -n -P'
alias git='hub'
# If the last character of the alias value is a blank, then the next command word following the alias is also checked for alias expansion.
alias sudo='sudo '
