# Alias
alias update='brew update && brew upgrade --all && npm update -g && softwareupdate -l && sudo softwareupdate -iva'
alias dotfiles-remove='~/.dotfiles/setup/remove.sh'
alias dotfiles-install='~/.dotfiles/setup/install.sh'
alias shellconfig='subl ~/.zshrc; subl ~/.bashrc'
alias preztoconfig='subl ~/.zpreztorc; subl ~/.zshenv; subl ~/.zprofile; subl ~/.zshrc; subl ~/.zshenv; subl ~/.zlogin; subl ~/.zlogout'
alias bashconfig='subl ~/.bash_profile; subl ~/.bashrc'
alias gitconfig='subl ~/.gitconfig; subl ~/.gitignore_global'
alias slt='subl'
alias c='clear'
alias wget='wget -c' # Resume wget by default
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localip='ipconfig getifaddr en0;ipconfig getifaddr en1;'
alias ls='ls -G'
alias ll='ls -l -a'
alias l.='ls -d -G .*'
alias npml='npm list -g --depth=0'
alias brewl='brew leaves'
alias showHidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideHidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias afk="open -a /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
export PATH="/usr/local/sbin:$PATH"
