#!/bin/bash

export PATH="/usr/local/sbin:$PATH"

if [ -f ~/.functions ]; then
   source ~/.functions
fi

if [ -f ~/.aliases ]; then
   source ~/.aliases
fi

if [ -f ~/.usershell ]; then
   source ~/.usershell
fi
