#!/bin/bash

# HOMEBREW
# http://brew.sh/
export PATH="/usr/local/sbin:$PATH"

# stop brew analytics ($brew analytics off)
export HOMEBREW_NO_ANALYTICS=1

# PHP
# export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"

# Composer
# https://getcomposer.org/
export PATH="$HOME/.composer/vendor/bin:$PATH"

# yarn
# https://yarnpkg.com/
export PATH="$PATH:`yarn global bin`"

# set default editor
export VISUAL="nano"
export EDITOR="nano"
