#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# add a space in front of a command to prevent it being added to history
setopt HIST_IGNORE_SPACE

# don't not store failed command in history
zshaddhistory() { whence ${${(z)1}[1]} >| /dev/null || return 1 }

if [ -f ~/.exports ]; then
   source ~/.exports
fi

if [ -f ~/.functions ]; then
   source ~/.functions
fi

if [ -f ~/.aliases ]; then
   source ~/.aliases
fi

if [ -f ~/.usershell ]; then
   source ~/.usershell
fi
